### ISSUE TITLE
Can this detect strain level differences or only at the species level?

### ISSUE THREAD

**Issue by harisankarsadasivan** [icthrm/cwSDTWnano#4]
For example, what if my reference signal is from ecoli strain 1, does csdtwnano (cwt based) distinguish ecoli strain 2 ?

**Comment by icthrm** [comment]
Thank you for your email. if there are only several SNPs, we cannot make it
(it is a phasing problem). If there are differences with long bps (for
example, 40 bp difference), we could make it.


harisankarsadasivan <notifications@github.com> 于2020年10月9日周五 下午11:36写道：
